In [8]:
import numpy as np

In [9]:
 nx, ny = (3, 2)

In [10]:
nx

3

In [11]:
ny

2

In [17]:
x = np.linspace(0, 1, nx)
y = np.linspace(0, 2, ny)

In [18]:
x,y

(array([ 0. ,  0.5,  1. ]), array([ 0.,  2.]))

In [22]:
xv = np.meshgrid(x, y)

In [23]:
xv

[array([[ 0. ,  0.5,  1. ],
        [ 0. ,  0.5,  1. ]]), array([[ 0.,  0.,  0.],
        [ 2.,  2.,  2.]])]

In [24]:
xv[0]

array([[ 0. ,  0.5,  1. ],
       [ 0. ,  0.5,  1. ]])

In [25]:
xv[1]

array([[ 0.,  0.,  0.],
       [ 2.,  2.,  2.]])